### Recuperar todos los usuarios
GET http://localhost:1235/api/users

### Crear un usuario
POST http://localhost:1235/api/users
Content-Type: application/json

{
  "username": "kskpluss",
  "email": "kskpluss@gmail.com",
  "password": "ksk123"
}

###Traer un usuario por el Id
GET http://localhost:1235/api/users/66a1c5df6d2c9ac1d92c703c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtza3BsdXNzIiwiaWQiOiI2NmExYzliNTMwZDgyZDU5NGJmZjljMWMiLCJpYXQiOjE3MjIwMDU2Njh9.q-1CJvIh064XbyFSh5zPqnvCpp0XMFyqOe-MPNeyLb12


### obtener todas las urls por el id del usuario
GET http://localhost:1235/api/users/66a1c9b530d82d594bff9c1c/urls
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtza3BsdXNzIiwiaWQiOiI2NmExYzliNTMwZDgyZDU5NGJmZjljMWMiLCJpYXQiOjE3MjIwMDU2Njh9.q-1CJvIh064XbyFSh5zPqnvCpp0XMFyqOe-MPNeyLb12